<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Authentication Routes
|--------------------------------------------------------------------------
|
| Placeholder auth route file. If Breeze/Jetstream routes are generated,
| this file can be replaced with framework-provided auth routes.
|
*/

Route::middleware('guest')->group(function (): void {
    // auth routes are generated by starter kits
});
